package com.yiwanjia.dao;

import com.yiwanjia.pojo.TbActivity;
import com.yiwanjia.pojo.TbActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    long countByExample(TbActivityExample example);
    int deleteByIdList(int[] id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    int deleteByExample(TbActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    int insert(TbActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    int insertSelective(TbActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    List<TbActivity> selectByExampleWithBLOBs(TbActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    List<TbActivity> selectByExample(TbActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    TbActivity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbActivity record, @Param("example") TbActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TbActivity record, @Param("example") TbActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbActivity record, @Param("example") TbActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TbActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbActivity record);
}