package com.yiwanjia.dao;

import com.yiwanjia.pojo.TbBanner;
import com.yiwanjia.pojo.TbBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_banner
     *
     * @mbggenerated
     */
    int countByExample(TbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_banner
     *
     * @mbggenerated
     */
    int deleteByExample(TbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_banner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_banner
     *
     * @mbggenerated
     */
    int insert(TbBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_banner
     *
     * @mbggenerated
     */
    int insertSelective(TbBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_banner
     *
     * @mbggenerated
     */
    List<TbBanner> selectByExample(TbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_banner
     *
     * @mbggenerated
     */
    TbBanner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_banner
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbBanner record, @Param("example") TbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_banner
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbBanner record, @Param("example") TbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_banner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_banner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbBanner record);
}