package com.yiwanjia.dao;

import com.yiwanjia.pojo.TbFooter;
import com.yiwanjia.pojo.TbFooterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFooterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    int countByExample(TbFooterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    int deleteByExample(TbFooterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    int insert(TbFooter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    int insertSelective(TbFooter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    List<TbFooter> selectByExample(TbFooterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    TbFooter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbFooter record, @Param("example") TbFooterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbFooter record, @Param("example") TbFooterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbFooter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbFooter record);
}