package com.yiwanjia.dao;

import com.yiwanjia.pojo.TbJoin;
import com.yiwanjia.pojo.TbJoinExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbJoinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_join
     *
     * @mbggenerated
     */
    int countByExample(TbJoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_join
     *
     * @mbggenerated
     */
    int deleteByExample(TbJoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_join
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_join
     *
     * @mbggenerated
     */
    int insert(TbJoin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_join
     *
     * @mbggenerated
     */
    int insertSelective(TbJoin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_join
     *
     * @mbggenerated
     */
    List<TbJoin> selectByExampleWithBLOBs(TbJoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_join
     *
     * @mbggenerated
     */
    List<TbJoin> selectByExample(TbJoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_join
     *
     * @mbggenerated
     */
    TbJoin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_join
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbJoin record, @Param("example") TbJoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_join
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TbJoin record, @Param("example") TbJoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_join
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbJoin record, @Param("example") TbJoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_join
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbJoin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_join
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TbJoin record);
}