package com.yiwanjia.dao;

import com.yiwanjia.pojo.TbNews;
import com.yiwanjia.pojo.TbNewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    int countByExample(TbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    int deleteByExample(TbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    int insert(TbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    int insertSelective(TbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    List<TbNews> selectByExampleWithBLOBs(TbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    List<TbNews> selectByExample(TbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    TbNews selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbNews record, @Param("example") TbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TbNews record, @Param("example") TbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbNews record, @Param("example") TbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbNews record);
}