package com.yiwanjia.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbContact implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contact.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contact.ContactName
     *
     * @mbggenerated
     */
    private String contactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contact.ContactContent
     *
     * @mbggenerated
     */
    private String contactcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contact.ContactCreate
     *
     * @mbggenerated
     */
    private Date contactcreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contact.ContactUpdate
     *
     * @mbggenerated
     */
    private Date contactupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_contact
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_contact.id
     *
     * @return the value of tb_contact.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_contact.id
     *
     * @param id the value for tb_contact.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_contact.ContactName
     *
     * @return the value of tb_contact.ContactName
     *
     * @mbggenerated
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_contact.ContactName
     *
     * @param contactname the value for tb_contact.ContactName
     *
     * @mbggenerated
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_contact.ContactContent
     *
     * @return the value of tb_contact.ContactContent
     *
     * @mbggenerated
     */
    public String getContactcontent() {
        return contactcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_contact.ContactContent
     *
     * @param contactcontent the value for tb_contact.ContactContent
     *
     * @mbggenerated
     */
    public void setContactcontent(String contactcontent) {
        this.contactcontent = contactcontent == null ? null : contactcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_contact.ContactCreate
     *
     * @return the value of tb_contact.ContactCreate
     *
     * @mbggenerated
     */
    public Date getContactcreate() {
        return contactcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_contact.ContactCreate
     *
     * @param contactcreate the value for tb_contact.ContactCreate
     *
     * @mbggenerated
     */
    public void setContactcreate(Date contactcreate) {
        this.contactcreate = contactcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_contact.ContactUpdate
     *
     * @return the value of tb_contact.ContactUpdate
     *
     * @mbggenerated
     */
    public Date getContactupdate() {
        return contactupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_contact.ContactUpdate
     *
     * @param contactupdate the value for tb_contact.ContactUpdate
     *
     * @mbggenerated
     */
    public void setContactupdate(Date contactupdate) {
        this.contactupdate = contactupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contact
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbContact other = (TbContact) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getContactname() == null ? other.getContactname() == null : this.getContactname().equals(other.getContactname()))
            && (this.getContactcontent() == null ? other.getContactcontent() == null : this.getContactcontent().equals(other.getContactcontent()))
            && (this.getContactcreate() == null ? other.getContactcreate() == null : this.getContactcreate().equals(other.getContactcreate()))
            && (this.getContactupdate() == null ? other.getContactupdate() == null : this.getContactupdate().equals(other.getContactupdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contact
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getContactname() == null) ? 0 : getContactname().hashCode());
        result = prime * result + ((getContactcontent() == null) ? 0 : getContactcontent().hashCode());
        result = prime * result + ((getContactcreate() == null) ? 0 : getContactcreate().hashCode());
        result = prime * result + ((getContactupdate() == null) ? 0 : getContactupdate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contact
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", contactname=").append(contactname);
        sb.append(", contactcontent=").append(contactcontent);
        sb.append(", contactcreate=").append(contactcreate);
        sb.append(", contactupdate=").append(contactupdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}