package com.yiwanjia.pojo;

import java.io.Serializable;

public class TbFooter implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_footer.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_footer.FooterTitle
     *
     * @mbggenerated
     */
    private String footertitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_footer.FooterName
     *
     * @mbggenerated
     */
    private String footername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_footer.FooterAddress
     *
     * @mbggenerated
     */
    private String footeraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_footer.FooterParent
     *
     * @mbggenerated
     */
    private Integer footerparent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_footer.FooterPID
     *
     * @mbggenerated
     */
    private Integer footerpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_footer.id
     *
     * @return the value of tb_footer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_footer.id
     *
     * @param id the value for tb_footer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_footer.FooterTitle
     *
     * @return the value of tb_footer.FooterTitle
     *
     * @mbggenerated
     */
    public String getFootertitle() {
        return footertitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_footer.FooterTitle
     *
     * @param footertitle the value for tb_footer.FooterTitle
     *
     * @mbggenerated
     */
    public void setFootertitle(String footertitle) {
        this.footertitle = footertitle == null ? null : footertitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_footer.FooterName
     *
     * @return the value of tb_footer.FooterName
     *
     * @mbggenerated
     */
    public String getFootername() {
        return footername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_footer.FooterName
     *
     * @param footername the value for tb_footer.FooterName
     *
     * @mbggenerated
     */
    public void setFootername(String footername) {
        this.footername = footername == null ? null : footername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_footer.FooterAddress
     *
     * @return the value of tb_footer.FooterAddress
     *
     * @mbggenerated
     */
    public String getFooteraddress() {
        return footeraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_footer.FooterAddress
     *
     * @param footeraddress the value for tb_footer.FooterAddress
     *
     * @mbggenerated
     */
    public void setFooteraddress(String footeraddress) {
        this.footeraddress = footeraddress == null ? null : footeraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_footer.FooterParent
     *
     * @return the value of tb_footer.FooterParent
     *
     * @mbggenerated
     */
    public Integer getFooterparent() {
        return footerparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_footer.FooterParent
     *
     * @param footerparent the value for tb_footer.FooterParent
     *
     * @mbggenerated
     */
    public void setFooterparent(Integer footerparent) {
        this.footerparent = footerparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_footer.FooterPID
     *
     * @return the value of tb_footer.FooterPID
     *
     * @mbggenerated
     */
    public Integer getFooterpid() {
        return footerpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_footer.FooterPID
     *
     * @param footerpid the value for tb_footer.FooterPID
     *
     * @mbggenerated
     */
    public void setFooterpid(Integer footerpid) {
        this.footerpid = footerpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbFooter other = (TbFooter) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFootertitle() == null ? other.getFootertitle() == null : this.getFootertitle().equals(other.getFootertitle()))
            && (this.getFootername() == null ? other.getFootername() == null : this.getFootername().equals(other.getFootername()))
            && (this.getFooteraddress() == null ? other.getFooteraddress() == null : this.getFooteraddress().equals(other.getFooteraddress()))
            && (this.getFooterparent() == null ? other.getFooterparent() == null : this.getFooterparent().equals(other.getFooterparent()))
            && (this.getFooterpid() == null ? other.getFooterpid() == null : this.getFooterpid().equals(other.getFooterpid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFootertitle() == null) ? 0 : getFootertitle().hashCode());
        result = prime * result + ((getFootername() == null) ? 0 : getFootername().hashCode());
        result = prime * result + ((getFooteraddress() == null) ? 0 : getFooteraddress().hashCode());
        result = prime * result + ((getFooterparent() == null) ? 0 : getFooterparent().hashCode());
        result = prime * result + ((getFooterpid() == null) ? 0 : getFooterpid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_footer
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", footertitle=").append(footertitle);
        sb.append(", footername=").append(footername);
        sb.append(", footeraddress=").append(footeraddress);
        sb.append(", footerparent=").append(footerparent);
        sb.append(", footerpid=").append(footerpid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}