package com.yiwanjia.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbGoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.GoodsTtile
     *
     * @mbggenerated
     */
    private String goodsttile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.UpdateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.GoodsDesc
     *
     * @mbggenerated
     */
    private String goodsdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.id
     *
     * @return the value of tb_goods.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.id
     *
     * @param id the value for tb_goods.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.GoodsTtile
     *
     * @return the value of tb_goods.GoodsTtile
     *
     * @mbggenerated
     */
    public String getGoodsttile() {
        return goodsttile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.GoodsTtile
     *
     * @param goodsttile the value for tb_goods.GoodsTtile
     *
     * @mbggenerated
     */
    public void setGoodsttile(String goodsttile) {
        this.goodsttile = goodsttile == null ? null : goodsttile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.image
     *
     * @return the value of tb_goods.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.image
     *
     * @param image the value for tb_goods.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.CreateTime
     *
     * @return the value of tb_goods.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.CreateTime
     *
     * @param createtime the value for tb_goods.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.UpdateTime
     *
     * @return the value of tb_goods.UpdateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.UpdateTime
     *
     * @param updatetime the value for tb_goods.UpdateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.GoodsDesc
     *
     * @return the value of tb_goods.GoodsDesc
     *
     * @mbggenerated
     */
    public String getGoodsdesc() {
        return goodsdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.GoodsDesc
     *
     * @param goodsdesc the value for tb_goods.GoodsDesc
     *
     * @mbggenerated
     */
    public void setGoodsdesc(String goodsdesc) {
        this.goodsdesc = goodsdesc == null ? null : goodsdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbGoods other = (TbGoods) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGoodsttile() == null ? other.getGoodsttile() == null : this.getGoodsttile().equals(other.getGoodsttile()))
            && (this.getImage() == null ? other.getImage() == null : this.getImage().equals(other.getImage()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
            && (this.getGoodsdesc() == null ? other.getGoodsdesc() == null : this.getGoodsdesc().equals(other.getGoodsdesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGoodsttile() == null) ? 0 : getGoodsttile().hashCode());
        result = prime * result + ((getImage() == null) ? 0 : getImage().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        result = prime * result + ((getGoodsdesc() == null) ? 0 : getGoodsdesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", goodsttile=").append(goodsttile);
        sb.append(", image=").append(image);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", goodsdesc=").append(goodsdesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}